### ISSUE TITLE
Template Compiler Error on bump from 0.13.0 to 0.14.0

### ISSUE THREAD

**Issue by Mifrill** [jkusa/ember-cli-clipboard#271]
**Describe the bug**

On bump from 0.13.0 to 0.14.0 get error:
```
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-cli-clipboard/templates/components/copy-button.hbs

Assertion Failed: '@aria-label' is not a valid path. ('ember-cli-clipboard/templates/components/copy-button.hbs' @ L2:C15) 
```

`package.json`: "ember-cli-clipboard": "0.13.0"

```
ember-cli-clipboard@0.13.0:
  version "0.13.0"
  resolved "https://registry.yarnpkg.com/ember-cli-clipboard/-/ember-cli-clipboard-0.13.0.tgz#47d3de3aec09987409c162cbff36f966a2c138b7"
  integrity sha512-AA2J5lliP/DXUFKnQ+r/D3e4xiN3ttlmN8W+8WfZg7K8VeOYlWpMyGcUjmuLa7inLUCMjLbtG6nXc20AQ5OjDg==
  dependencies:
    broccoli-funnel "^1.1.0"
    clipboard "^2.0.0"
    ember-cli-babel "^7.7.3"
    ember-cli-htmlbars "^3.0.1"
    fastboot-transform "^0.1.3"
```

**To Reproduce**
1. yarn upgrade ember-cli-clipboard@0.14.0
2. ember s

<details>
<summary>Stack trace</summary>

```
/home/mifrill/.nvm/versions/node/v10.16.1/bin/node /media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/.bin/ember serve --proxy=http://api.smhw.local
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-content-security-policy/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-build/index.js:4:15)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-display-revisions/lib/scm-table.js:6:18)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-display-revisions/lib/legacy-table.js:4:18)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-gzip/index.js:4:17)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-s3/index.js:4:17)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-s3/lib/s3.js:7:18)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-redis/index.js:4:17)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-manifest/index.js:4:17)
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here: 
  Object.<anonymous> (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-deploy-revision-data/index.js:4:15)
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
WARNING: Node v10.16.1 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
DEPRECATION: Addon files were detected in `/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-cli-stained-by-children/addon`, but no JavaScript preprocessors were found for `stained-by-children`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `stained-by-children`'s `package.json`.
Proxying to http://api.smhw.local
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-cli-clipboard/templates/components/copy-button.hbs

Assertion Failed: '@aria-label' is not a valid path. ('ember-cli-clipboard/templates/components/copy-button.hbs' @ L2:C15) 


Stack Trace and Error Report: /tmp/error.dump.28cf301160ce12606ec8a50ceb1a2577.log
cleaning up...

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

</details>

<details>
<summary>/tmp/error.dump.28cf301160ce12606ec8a50ceb1a2577.log</summary>

```
 cat /tmp/error.dump.28cf301160ce12606ec8a50ceb1a2577.log
=================================================================================

ENV Summary:

  TIME: Fri Oct 23 2020 15:06:06 GMT+0500 (Yekaterinburg Standard Time)
  TITLE: ember
  ARGV:
  - /home/mifrill/.nvm/versions/node/v10.16.1/bin/node
  - /media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/.bin/ember
  - serve
  - --proxy=http://api.smhw.local
  EXEC_PATH: /home/mifrill/.nvm/versions/node/v10.16.1/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/mifrill/.local/bin
  - /home/mifrill/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  PLATFORM: linux x64
  FREEMEM: 300683264
  TOTALMEM: 33728884736
  UPTIME: 153846
  LOADAVG: 2.9306640625,2.369140625,2.40185546875
  CPUS:
  - AMD FX(tm)-8350 Eight-Core Processor - 4126
  - AMD FX(tm)-8350 Eight-Core Processor - 4122
  - AMD FX(tm)-8350 Eight-Core Processor - 4126
  - AMD FX(tm)-8350 Eight-Core Processor - 4124
  - AMD FX(tm)-8350 Eight-Core Processor - 4126
  - AMD FX(tm)-8350 Eight-Core Processor - 4127
  - AMD FX(tm)-8350 Eight-Core Processor - 4127
  - AMD FX(tm)-8350 Eight-Core Processor - 4126
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 4
  - nghttp2: 1.34.0
  - node: 10.16.1
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Assertion Failed: '@aria-label' is not a valid path. ('ember-cli-clipboard/templates/components/copy-button.hbs' @ L2:C15) 
    at /media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:6482:13
    at PathExpression (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:14506:52)
    at visitNode (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2404:36)
    at visitKey (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2444:23)
    at visitNode (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
    at visitKey (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2444:23)
    at visitNode (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
    at visitArray (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2461:22)
    at visitKey (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2442:13)
    at visitNode (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
  - code: [undefined]
  - codeFrame: Assertion Failed: '@aria-label' is not a valid path. ('ember-cli-clipboard/templates/components/copy-button.hbs' @ L2:C15) 
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:TemplateCompiler` plugin. 💥
Assertion Failed: '@aria-label' is not a valid path. ('ember-cli-clipboard/templates/components/copy-button.hbs' @ L2:C15) 
  - errorType: Template Compiler Error
  - location:
    - column: [undefined]
    - file: ember-cli-clipboard/templates/components/copy-button.hbs
    - line: [undefined]
    - treeDir: /media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/tmp/broccoli_persistent_filtertemplate_compiler-input_base_path-otnpSYQ5.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:TemplateCompiler` plugin. 💥
Assertion Failed: '@aria-label' is not a valid path. ('ember-cli-clipboard/templates/components/copy-button.hbs' @ L2:C15) 
  - name: Error
  - nodeAnnotation: broccoli-persistent-filter:TemplateCompiler
  - nodeName: broccoli-persistent-filter:TemplateCompiler
  - originalErrorMessage: Assertion Failed: '@aria-label' is not a valid path. ('ember-cli-clipboard/templates/components/copy-button.hbs' @ L2:C15) 
  - stack: Error: Assertion Failed: '@aria-label' is not a valid path. ('ember-cli-clipboard/templates/components/copy-button.hbs' @ L2:C15) 
    at /media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:6482:13
    at PathExpression (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:14506:52)
    at visitNode (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2404:36)
    at visitKey (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2444:23)
    at visitNode (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
    at visitKey (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2444:23)
    at visitNode (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)
    at visitArray (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2461:22)
    at visitKey (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2442:13)
    at visitNode (/media/mifrill/236bf183-17ec-4844-aea7-e9418f4b1cea1/code/show-app/frontend/smhw-frontend/node_modules/ember-source/dist/ember-template-compiler.js:2419:17)

=================================================================================

```

</details>

**Additional context**
"ember-source": version "2.14.1"
"broccoli-asset-rev": "^3.0.0"
```
broccoli-asset-rev@^3.0.0:
  version "3.0.0"
  resolved "https://registry.yarnpkg.com/broccoli-asset-rev/-/broccoli-asset-rev-3.0.0.tgz#65a28c8a062d6ee2cffd91ed2a8309e0f8253ac6"
  integrity sha512-gAHQZnwvtl74tGevUqGuWoyOdJUdMMv0TjGSMzbdyGImr9fZcnM6xmggDA8bUawrMto9NFi00ZtNUgA4dQiUBw==
  dependencies:
    broccoli-asset-rewrite "^2.0.0"
    broccoli-filter "^1.2.2"
    broccoli-persistent-filter "^1.4.3"
    json-stable-stringify "^1.0.0"
    minimatch "^3.0.4"
    rsvp "^3.0.6"
```

**Comment by jkusa** [comment]
Not sure if this is still an issue. [v1.0.0](https://github.com/jkusa/ember-cli-clipboard/releases/tag/v1.0.0) removed `@aria-label` as a component argument. (You now can set `aria-label` as a component attribute)

I am going to close this issue for now. Please reopen if needed.

**Comment by Mifrill** [comment]
@jkusa yes, it is still an issue, because v1.0.0 cannot be used for the legacy ember version that is involved in this particular issue.

**Comment by jkusa** [comment]
@Mifrill got it.

Looks like a similar error was discovered in https://github.com/cibernox/ember-basic-dropdown/issues/485 with an older ember application and a newer addon version

Are you invoking the component with angle brackets? Also, is there a feature you are looking to leverage in > 0.13.0?

**Comment by Mifrill** [comment]
@jkusa 
> Are you invoking the component with angle brackets?

I've tried both. For angle brackets I've used latest version of https://github.com/ember-polyfills/ember-angle-bracket-invocation-polyfill.

> is there a feature you are looking to leverage in > 0.13.0?

Not something special, just 'd like to keep packages up to date, as path of the entire upgrade of ember app.
