### ISSUE TITLE
Ember build fails after including the addon

### ISSUE THREAD

**Issue by dipayanb** [jkusa/ember-cli-clipboard#9]
After including the plugin, `ember build` fails with the following error:
```
➜  testapp git:(master) ✗ ember build
version: 2.2.0-beta.4
Build failed.
ENOENT, no such file or directory '/Users/dbhowmick/personal/development/temp/testapp/tmp/source_map_concat-input_base_path-NwLjvJJY.tmp/0/bower_components/clipboard/dist/clipboard.js'
Error: ENOENT, no such file or directory '/Users/dbhowmick/personal/development/temp/testapp/tmp/source_map_concat-input_base_path-NwLjvJJY.tmp/0/bower_components/clipboard/dist/clipboard.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at ConcatWithMaps.keyForFile (/Users/dbhowmick/personal/development/temp/testapp/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/dbhowmick/personal/development/temp/testapp/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/dbhowmick/personal/development/temp/testapp/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/dbhowmick/personal/development/temp/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dbhowmick/personal/development/temp/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/dbhowmick/personal/development/temp/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/dbhowmick/personal/development/temp/testapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

package.json:
```json
{
  "name": "testapp",
  "version": "0.0.0",
  "description": "Small description for testapp goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.2.0-beta.4",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.1.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.0.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.2.1",
    "ember-cli-clipboard": "^0.3.1",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-resolver": "^2.0.3"
  }
}
```

bower.json:

```json
{
  "name": "testapp",
  "dependencies": {
    "ember": "2.2.0",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-load-initializers": "0.1.7",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "1.11.3",
    "loader.js": "^3.5.0",
    "qunit": "~1.20.0"
  },
  "resolutions": {
    "ember": "2.2.0"
  }
}
```

```
➜  testapp git:(master) ✗ ember -v
version: 2.2.0-beta.4
node: 0.12.7
npm: 2.14.10
os: darwin x64
```

The problem seems to be the https://github.com/jkusa/ember-cli-clipboard/blob/master/index.js#L15 which mixes with the application path and tries to import `clipboard.js` from the bower directory of the including application.

Hence as a workaround, I am adding `"clipboard": "~1.5.5"` as a dependency in `testapp` bower.json.

So this configuration of `bower.json` works:
```json
{
  "name": "testapp",
  "dependencies": {
    "ember": "2.2.0",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-load-initializers": "0.1.7",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "1.11.3",
    "loader.js": "^3.5.0",
    "qunit": "~1.20.0",
    "clipboard": "~1.5.5"
  },
  "resolutions": {
    "ember": "2.2.0"
  }
}
```

**Comment by dipayanb** [comment]
Sorry, this got resolved. I did not install the addon using `ember install`, rather copied from another project(where the actual issue came) and the clipboard dependency was missing in its `bower.json`. And hence the clipboard dependency was not found.

Removed `node_modules` and `bower_components` and executed `ember install ember-cli-clipboard`. Things started working fine.
